title: Ravi Seth
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rksseth.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Ravi Seth # add your name
author-img: ravi-seth.png # add your photo
about-author: Hello!  I am a <b>Full Stack Developer</b> looking for a <b>Summer 2020</b> internship. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: rksseth # add your Github handle
social-linkedin: rksseth # add your Linkedin handle
social-email: ravi.seth@uwaterloo.ca # add your Email address

# Disqus
discus-identifier: anonymous # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
